In [1]:
#%pip install numpy

In [2]:
import numpy as np
np.__version__

'2.0.2'

In [3]:
my_list = [1, 2, 3, 4, 5]
my_np_array = np.array(my_list)
print(my_list, type(my_list))
print(my_np_array, type(my_np_array))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
my_np_array.shape

(5,)

In [5]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [6]:
arr = np.array([1, 2, 3], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3]]]]]
number of dimensions : 5


In [7]:
arr = np.array([[1,2,3],[4,5,6]])
print("2nd element of first row: ", arr[0,1])
print("2nd element of first row: ", arr[0][1])

2nd element of first row:  2
2nd element of first row:  2


In [8]:
arr = np.array([
    [[1, 2, 3], [4, 5, 6]], #first array
    [[7, 8, 9], [10, 11, 12]] #second array
    ])
print(arr.shape)
print("2nd element of 4th row = ", arr[1, 1, 1])

(2, 2, 3)
2nd element of 4th row =  11


In [9]:
arr = np.array([10, 20, 30, 5, 10, 51])
filter_mask = [True, True, True, False, False, True]
filtered_array = arr[filter_mask]
print(filtered_array) #showing only the true
print(arr[[0, 1, 2, 5]]) #another way to filter using index

[10 20 30 51]
[10 20 30 51]


In [10]:
odd_mask = arr % 2
odd_mask = odd_mask.astype('bool')
print(odd_mask)
print(arr[odd_mask]) #only odd elements
print(arr[arr % 2 != 0]) #same in a single line

[False False False  True False  True]
[ 5 51]
[ 5 51]


In [11]:
w = np.ones(
    shape=(2, 2, 2)
)
x = np.zeros(
    shape=(2, 2, 2)
)

x*w # Elementwise multiplication


array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [12]:
w = np.array([1, 2, 3])
x = np.array([4, 5, 6])

print(w + x)

[5 7 9]


In [13]:
w = np.array([[1,2,3],[4,5,6]]) # 2D array, shape = (2, 3) - 2 rows and 3 columns
x = np.array([1,2,3]) # 1D array, shape = (3,) - 3 rows and 1 column
# expand x to match the shape of w 
# x will be broadcasted to (2, 3) to match w 
# x = np.array([[1,2,3],[1,2,3]]) - this is called broadcasting
print(w+x)

[[2 4 6]
 [5 7 9]]


In [14]:
myArr = np.array([
    [1,2,3],
    [4,5,6]
    ])
print(myArr)

[[1 2 3]
 [4 5 6]]


In [15]:
print(np.sum(myArr)) # sum of all elements

21


In [16]:
print(np.sum(myArr, axis=0)) # sum of all columns / first dimension

[5 7 9]


In [17]:
print(np.sum(myArr, axis=1)) # sum of each row / second dimension

[ 6 15]


In [18]:
my_array = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ],
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ],
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ]
    ]
)

print(my_array.shape)

(3, 3, 3)


In [19]:
print(np.sum(my_array, axis=0)) # 3 different 2D arrays will be a single 2D array
# 1 + 1 + 1 = 3
# 2 + 2 + 2 = 6
# 3 + 3 + 3 = 9 ..... continue

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [20]:
print(np.sum(my_array, axis=1)) # column wise sum in each 2D array
# 1 + 4 + 7 = 12
# 2 + 5 + 8 = 15
# 3 + 6 + 9 = 18 .... contine

[[12 15 18]
 [12 15 18]
 [12 15 18]]


In [21]:
print(np.sum(my_array, axis=2))# row wise sum in each 2D array
# 1 + 2 + 3 = 6
# 4 + 5 + 6 = 15
# 7 + 8 + 9 = 24 ... continue

[[ 6 15 24]
 [ 6 15 24]
 [ 6 15 24]]


In [22]:
print(np.random.rand()) # random float between 0 and 1
print(np.random.rand(2, 5)) # random float between 2 and 5
print(type(np.random.rand(5))) # type of the array
print(np.random.randint(100)) # random integer between 0 and 100
print(np.random.randint(100, size=(2, 5))) # random integer between 0 and 100 with size 2x5


0.04370475551290132
[[0.87529972 0.01743892 0.77646525 0.30858189 0.42470079]
 [0.91356972 0.96121828 0.38617535 0.94138712 0.61589882]]
<class 'numpy.ndarray'>
58
[[74 63 14 68 49]
 [75 11 69 11 95]]


In [23]:
probabilities = np.array([0.7, 0.9, 0.1, 0.2, 0.7, 0.8, 0.3, 0.4])
print(f"Sorted Probabilities: {np.sort(probabilities)}") # sorted array ascending order
print(f" Reverse Sorted Probabilities: {np.sort(probabilities)[::-1]}") # sorted array descending order
print(f"Max Probability: {np.max(probabilities)}") # maximum value
print(f"Min Probability: {np.min(probabilities)}") # minimum value
print(f"Index of Max Probability: {np.argmax(probabilities)}") # index of max value
print(f"Index of Min Probability: {np.argmin(probabilities)}") # index of min value


Sorted Probabilities: [0.1 0.2 0.3 0.4 0.7 0.7 0.8 0.9]
 Reverse Sorted Probabilities: [0.9 0.8 0.7 0.7 0.4 0.3 0.2 0.1]
Max Probability: 0.9
Min Probability: 0.1
Index of Max Probability: 1
Index of Min Probability: 2


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_arr = np.split(
    arr,
    indices_or_sections=4
)
print(new_arr)
print(new_arr[0])
print(new_arr[1])
print(new_arr[2])
print(new_arr[3])



[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
