In [78]:
""" Class 15. Introduction to Deep Learning and Perceptron

Objectives:
- Understand the structure and functionality of the perceptron
- Implement a perceptron
- Train a model for binary classification

Project Objectives:
- How to identify research questions
- How to perform Literature Review

Requirement: A Research Proposal
Prompt: 
    Act as harvard professor and my supervisor. 
    Given the project proposal, find a list of research questions
    that each RQ can be experimented or answered within 2 weeks max.

Assignment:
 1. Identify 5-10 research questions
 2. Pick a research question
 3. Find 4-5 relevant research papers
 4. Review each research paper with respect to picked research question.

nn module: neural network
"""
import numpy as np
import torch
import torch.nn as nn

In [52]:
X = np.array([
    [0.0, 0.0],
    [0.0, 1.0],
    [1.0, 0.0],
    [1.0, 1.0],
])
print(type(X))

<class 'numpy.ndarray'>


In [53]:
X = torch.tensor(X)
print(type(X)) # <class torch.Tensor>

<class 'torch.Tensor'>


In [54]:
np.random.rand(5)

array([0.03641435, 0.7807862 , 0.91807606, 0.29865843, 0.43872621])

In [55]:
my_tensor = torch.rand(5)
print(my_tensor)

tensor([0.4972, 0.0169, 0.7511, 0.3669, 0.0796])


In [56]:
my_tensor.sum(axis=0)

tensor(1.7118)

In [57]:
torch.randn(3)

tensor([ 0.6260, -1.2588,  0.3220])

In [58]:
""" Parameter
"""
nn.Parameter(torch.randn(3))

Parameter containing:
tensor([ 0.5548,  1.7304, -0.3953], requires_grad=True)

In [ ]:
"""
X = [x1, x2, x3]
W = [w1, w2, w3]
b
y_pred = x1 * w1 + x2 * w2 + x3 * w3 + b // linear or nonlinear? -> linear
- linear equation can not detect nonlinear patterns
- ax^2 + bx + c is non linear equation of degree 2
- ax^3 + bx^2 + cx + d is non linear equation of degree 3

Increasing nonlinearity means increasing model complexity
Increasing model complexity model will learn better non-linearity

y_pred = Non linear Activation function(x1 * w1 + x2 * w2 + x3 * w3 + b)
"""

class Perceptron(nn.Module):
    def __init__(self, input_size):
        super(Perceptron, self).__init__()
        self.input_size = input_size
        
        self.weight = nn.Parameter(torch.randn(input_size))
        self.bias = nn.Parameter(torch.zeros(1))
        print(self.weight, self.bias)
        
    def forward(self, x):
        z = x @ self.weight + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
perceptron = Perceptron(3)

Parameter containing:
tensor([ 0.7146, -0.1030, -0.9877], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)


In [60]:
w = torch.Tensor([1, 2, 3])
x = torch.Tensor([2, 3, 4])
x @ w

tensor(20.)

In [61]:
import os

model = Perceptron(input_size=3)
model_path = 'my_model.pth'

if os.path.exists(model_path):
    model.load_state_dict(torch.load(model_path))
    print('Model loaded')

Parameter containing:
tensor([-1.0291, -1.1550, -0.5667], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)
Model loaded


In [62]:
x = torch.randn(3)
print(x)

tensor([0.9976, 1.3414, 1.3093])


In [63]:
y_pred = model(x)
print(y_pred)

tensor([0.9922], grad_fn=<SigmoidBackward0>)


In [64]:
print(*model.parameters())

Parameter containing:
tensor([0.9185, 0.9185, 5.0429], requires_grad=True) Parameter containing:
tensor([-3.8992], requires_grad=True)


In [65]:
""" Cost function
"""
criterion = nn.BCELoss() # Binary cross entropy loss

""" Optimizers """
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.0001
)

In [66]:
X = torch.Tensor(
    [
        [0.0, 0.0, 0.0], # sample input 1 (x1, x2, x3)
        [0.0, 1.0, 0.0], # sample input 2
        [1.0, 0.0, 0.0], # sample input 3
        [1.0, 1.0, 1.0]  # sample input 4
    ]
)

Y = torch.Tensor(
    [
        [0.0], # sample output 1
        [0.0], # sample output 2
        [0.0], # sample output 3
        [1.0]  # sample output 4
    ]
)

In [67]:
y_preds = model(X)
print(y_preds.shape)

torch.Size([4])


In [68]:
print(y_preds)

tensor([0.0199, 0.0483, 0.0483, 0.9517], grad_fn=<SigmoidBackward0>)


In [69]:
y_preds.ndim

1

In [70]:
y_preds = y_preds.unsqueeze(axis=1)
print(y_preds)

tensor([[0.0199],
        [0.0483],
        [0.0483],
        [0.9517]], grad_fn=<UnsqueezeBackward0>)


In [71]:
def train_model(model, epochs):
    for epoch in range(epochs):
        """ Prediction (Forward Propagation) """
        y_pred = model(X)
        
        """ Loss calculation """
        loss = criterion(y_pred.unsqueeze(axis=1), Y)

        """ Calculate gradient """
        optimizer.zero_grad()
        loss.backward() # (Backward propagation)

        """ Update weight """
        optimizer.step() # w1 = w1 - lr * dw1
        
        if epoch % 1000 == 0:
            print(f'Epoch: {epoch}, Loss: {loss.item():.4f}')

In [72]:
train_model(model, 20000)

Epoch: 0, Loss: 0.0421
Epoch: 1000, Loss: 0.0394
Epoch: 2000, Loss: 0.0368
Epoch: 3000, Loss: 0.0345
Epoch: 4000, Loss: 0.0323
Epoch: 5000, Loss: 0.0303
Epoch: 6000, Loss: 0.0284
Epoch: 7000, Loss: 0.0266
Epoch: 8000, Loss: 0.0250
Epoch: 9000, Loss: 0.0234
Epoch: 10000, Loss: 0.0220
Epoch: 11000, Loss: 0.0206
Epoch: 12000, Loss: 0.0193
Epoch: 13000, Loss: 0.0181
Epoch: 14000, Loss: 0.0170
Epoch: 15000, Loss: 0.0159
Epoch: 16000, Loss: 0.0150
Epoch: 17000, Loss: 0.0140
Epoch: 18000, Loss: 0.0132
Epoch: 19000, Loss: 0.0123


In [73]:
print(*model.parameters())

Parameter containing:
tensor([1.5364, 1.5364, 6.9313], requires_grad=True) Parameter containing:
tensor([-5.7703], requires_grad=True)


In [74]:
""" Mode of a torch model

By default: train
We can set the mode to eval during prediction
"""
def predict(model, X):
    model.eval()
    with torch.no_grad():
        test_output = model(X)
    return test_output

predict(model, X)

tensor([0.0031, 0.0143, 0.0143, 0.9857])

In [75]:
Y

tensor([[0.],
        [0.],
        [0.],
        [1.]])

In [76]:
model.state_dict()

OrderedDict([('weight', tensor([1.5364, 1.5364, 6.9313])),
             ('bias', tensor([-5.7703]))])

In [77]:
torch.save(model.state_dict(), 'my_model.pth')