In [113]:
#Mac: pip3 install torch torchvision

In [114]:
import numpy as np
import torch
import torch.nn as nn

In [115]:
#normal numpy array
X = np.array([
    [0.0, 0.0],
    [0.0, 1.0],
    [1.0, 0.0],
    [1.0, 1.0],
])
print(type(X))

<class 'numpy.ndarray'>


In [116]:
# convert the np array to py torch tensor
X = torch.tensor(X)
print(type(X))

<class 'torch.Tensor'>


In [117]:
np.random.rand(5) #random array

array([0.36743248, 0.57077707, 0.77797515, 0.65234315, 0.22347246])

In [118]:
my_tensor = torch.rand(5) #random tensor array
print(my_tensor)

tensor([0.7894, 0.3610, 0.0077, 0.2604, 0.8600])


In [119]:
my_tensor.sum(axis=0) #sum of the tensor array

tensor(2.2785)

In [120]:
torch.randn(3) #pull random numbers from normal distribution where std = 1, mean = 0

tensor([0.3156, 0.5535, 0.6693])

In [121]:
# Neural Network Parameter
nn.Parameter(torch.randn(3)) # requires_grad=True -> during training, these parameters will be optimized and calculate gradient

Parameter containing:
tensor([ 0.6506,  0.7705, -1.3090], requires_grad=True)

In [ ]:
#Define Perceptron, we need input(x), weights(w), bias(b), calculation(z), activation function
class Perceptron(nn.Module):
    def __init__(self, input_size):
        super(Perceptron, self).__init__() #We want the features of nn.Module in our parent class Perceptron. Without this, PyTorch will not understand
                                           # that it's a neural network

        self.input_size = input_size #store total no of input(x) size or no of features in each input

        self.weight = nn.Parameter(torch.randn(input_size)) #we know, all input (X) has an corresponding weigh(W). so, input_size == no of weight
        self.bias = nn.Parameter(torch.zeros(1)) #Without bias (b), all result will went through origin. bias create flexibity [can shift anywhere]
                                                 #nn.Parameter() -> Trainable Parameters (will apply optimizer, gradient, etc.)

        print(self.weight, self.bias)

    def forward(self, x): #Here, we'll write the prediction logics
        z = x @ self.weight + self.bias #@ means matrix multiplication / dot product and z = X.W + b = x1w1  + x2w2 + ---- + xnwn + b
        y_pred = torch.sigmoid(z) #push/insert the result(z) to a non-linear activation function 'sigmoid'. Introduce non-linearity.
                                  #Why sigmoid? -> Useful for binary classification. 0 → negative and 1 → positive
        return y_pred

# When ever well call perceptron(x), internally PyTorch calls forward(x)

perceptron = Perceptron(3) #here, x = [x1, x2, x3] -> 3 features

Parameter containing:
tensor([ 1.1487,  0.4334, -1.2934], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)


In [ ]:
x = torch.tensor([1.0, 2.0, 3.0])
output = perceptron(x) #When ever we'll call perceptron(x), internally PyTorch calls forward(x)
print(output)

tensor([0.1341], grad_fn=<SigmoidBackward0>)


In [124]:
#Define model
import os

model = Perceptron(input_size=3) #input_size = 3 means 3 features in each input
model_path = 'my_model.pth' #define a path for save our model

if os.path.exists(model_path):
    model.load_state_dict(torch.load(model_path)) #load if there is any existing learned model. Sometimes we face interruped and we need to restart. 
                                                  #So, using this method, we can start with existing situation so that we don't need to start from beginning.
    print("Model Loaded...")

Parameter containing:
tensor([-1.0872, -0.1003, -0.2467], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)
Model Loaded...


In [125]:
#input(x)
x = torch.randn(3)
print(x)

tensor([ 1.0932, -1.3281,  0.4498])


In [126]:
#prediction/output(y)
y_pred = model(x)
print(y_pred)

tensor([0.0661], grad_fn=<SigmoidBackward0>)


In [127]:
#see the parameters of our model
print(*model.parameters())

Parameter containing:
tensor([-0.3142,  1.3949,  0.0475], requires_grad=True) Parameter containing:
tensor([-0.4729], requires_grad=True)


In [128]:
# Cost Function
criterion = nn.BCELoss() #Bynary Cross Entropy Loss - used for binary classification

#Optimizer - used for optimize the loss/cost
optimizer = torch.optim.Adam(
    model.parameters(), #we need to optimize the model's parameters
    lr=0.0001 #define learning rate
)

In [129]:
# select input (X), output (Y)
X = torch.Tensor(
    [
        [0.0, 0.0, 0.0], # sample input 1 (x1, x2, x3)
        [0.0, 1.0, 0.0], # sample input 2
        [1.0, 0.0, 0.0], # sample input 3
        [1.0, 1.0, 1.0]  # sample input 4
    ]
) #shape (4, 3) -> Row/Batch size 4 (total input), Col 3 (no of features in each sample). Batch processing: (4,3)⋅(3,)=(4,)
# (batch_size, features) = (4,3)

Y = torch.Tensor(
    [
        [0.0], # sample output 1
        [0.0], # sample output 2
        [0.0], # sample output 3
        [1.0]  # sample output 4
    ]
)

In [130]:
y_pred = model(X) # means perceptron.forward(X)
print(y_pred)

tensor([0.3839, 0.7155, 0.3128, 0.6582], grad_fn=<SigmoidBackward0>)


In [131]:
print(y_pred.ndim)
print(y_pred)
y_pred = y_pred.unsqueeze(axis=1) #unsqueeze() -> add a dimension. We did this for creating a batch output. 
                                  #eural networks standardize tensors as (batch_size, output_features)
print(y_pred.ndim)
print(y_pred)
y_pred = y_pred.unsqueeze(axis=1) # unsqueeze() -> add a dimension
print(y_pred.ndim)
print(y_pred)

1
tensor([0.3839, 0.7155, 0.3128, 0.6582], grad_fn=<SigmoidBackward0>)
2
tensor([[0.3839],
        [0.7155],
        [0.3128],
        [0.6582]], grad_fn=<UnsqueezeBackward0>)
3
tensor([[[0.3839]],

        [[0.7155]],

        [[0.3128]],

        [[0.6582]]], grad_fn=<UnsqueezeBackward0>)


In [ ]:
#model training
def train_model(model, epochs):
    for epoch in range(epochs):
        """ Prediction (Forward Propagation) """
        y_pred = model(X) # (Forward propagation) -> produce input to output
        
        """ Loss calculation """
        loss = criterion(y_pred.unsqueeze(axis=1), Y) # calculate loss using predict output(y_pred) and true output Y (original)

        """ Calculate gradient """
        optimizer.zero_grad() #finding the optimal points [local minima] where loss is minimum
        loss.backward() # (Backward propagation)

        """ Update weight """
        optimizer.step() # w1 = w1 - lr * dw1, here, lr = steps, dw = direction
        
        if epoch % 1000 == 0:
            print(f'Epoch: {epoch}, Loss: {loss.item():.4f}')

In [133]:
train_model(model, 5000)

Epoch: 0, Loss: 0.6337
Epoch: 1000, Loss: 0.5902
Epoch: 2000, Loss: 0.5502
Epoch: 3000, Loss: 0.5135
Epoch: 4000, Loss: 0.4798


In [134]:
print(*model.parameters())

Parameter containing:
tensor([0.1590, 0.9476, 0.5455], requires_grad=True) Parameter containing:
tensor([-0.9498], requires_grad=True)


In [135]:
#Model Evaluation
""" Mode of a torch model

By default: train
We can set the mode to eval during prediction
"""
def predict(model, X):
    model.eval() # without evaluation mode, it will calculate gradient which is very time consuming and unnecessary. 
    with torch.no_grad():
        test_output = model(X)
    return test_output

predict(model, X)

tensor([0.2789, 0.4994, 0.3120, 0.6687])

In [136]:
# actual output
Y

tensor([[0.],
        [0.],
        [0.],
        [1.]])

In [137]:
model.state_dict() #crate weigh, bias dictonary, [key, value] pair

OrderedDict([('weight', tensor([0.1590, 0.9476, 0.5455])),
             ('bias', tensor([-0.9498]))])

In [138]:
torch.save(model.state_dict(), 'my_model.pth') # save the model's weights and bias in the specific path
# if we re-run from beginning, out model will start from previous/saved weight, bias. It will improve from previous. 

## Notebook Explanation (বাংলা)

এই section-এ উপরের সব code block বিস্তারিতভাবে explain করা হলো, যাতে notebook-এর পুরো flow, perceptron concept, formula, math intuition, এবং PyTorch workflow পরিষ্কারভাবে বোঝা যায়।

---

## 1. এই notebook-এর main goal কী?

এই notebook-এর মূল উদ্দেশ্য হলো deep learning-এর একদম basic building block **Perceptron** শেখানো। এখানে দেখানো হয়েছে কীভাবে:

- NumPy array থেকে PyTorch tensor-এ যেতে হয়
- random tensor তৈরি করতে হয়
- trainable parameter define করতে হয়
- custom neural network model তৈরি করতে হয়
- forward pass কাজ করে
- sigmoid activation apply হয়
- loss calculate হয়
- optimizer weight update করে
- model train, evaluate, save, load করা হয়

সহজভাবে: এই notebook deep learning-এর একটি end-to-end mini example।

---

## 2. Perceptron কী?

Perceptron হলো neural network-এর সবচেয়ে basic unit। এটি input নেয়, weight দিয়ে multiply করে, bias add করে, তারপর activation function দিয়ে output দেয়।

### Formula

যদি input হয়:

\[x = [x_1, x_2, x_3]\]

weight হয়:

\[w = [w_1, w_2, w_3]\]

bias হয়:

\[b\]

তাহলে perceptron-এর linear output:

\[z = x_1w_1 + x_2w_2 + x_3w_3 + b\]

vector form-এ:

\[z = XW + b\]

তারপর sigmoid activation:

\[\hat{y} = \sigma(z) = \frac{1}{1 + e^{-z}}\]

এখানে `ŷ` হচ্ছে predicted probability।

---

## 3. Code Block by Block Explanation

### Cell 0
`#Mac: pip3 install torch torchvision`

এটি setup note। এর কাজ PyTorch install করার command মনে রাখা। `torch` deep learning-এর core framework, আর `torchvision` vision utility package। এই notebook-এ মূলত `torch` লাগবে।

### Cell 1
```python
import numpy as np
import torch
import torch.nn as nn
```
এখানে তিনটি library import করা হয়েছে।

- `numpy` numerical array এবং matrix operation-এর জন্য
- `torch` tensor, autograd, training workflow-এর জন্য
- `torch.nn` custom neural network model, parameter, loss function define করার জন্য

### Cell 2
এখানে একটি `NumPy array` তৈরি করা হয়েছে:

```python
X = np.array([
    [0.0, 0.0],
    [0.0, 1.0],
    [1.0, 0.0],
    [1.0, 1.0],
])
```
এটি shape `(4, 2)`। মানে 4টি sample, প্রতিটিতে 2টি feature।

এখানে `print(type(X))` দিয়ে verify করা হচ্ছে যে এটি `numpy.ndarray` কি না।

### Cell 3
এখানে NumPy array-কে PyTorch tensor-এ convert করা হয়েছে:

```python
X = torch.tensor(X)
```
কারণ PyTorch model tensor নিয়ে কাজ করে, NumPy array নিয়ে না। Tensor deep learning-এর main data structure।

### Cell 4
`np.random.rand(5)` 5টি random number generate করে `[0,1)` range থেকে। এটি uniform distribution-এর example।

### Cell 5
`torch.rand(5)` একইভাবে 5টি random number দিয়ে একটি tensor তৈরি করে। এখানে NumPy array বনাম PyTorch tensor-এর random creation compare করা হয়েছে।

### Cell 6
`my_tensor.sum(axis=0)` tensor-এর সব value sum করছে। এটি basic tensor operation-এর example।

### Cell 7
`torch.randn(3)` normal distribution থেকে 3টি random value নেয়। অর্থাৎ mean = 0 এবং std = 1। Weight initialization-এ normal distribution খুব common।

### Cell 8
`nn.Parameter(torch.randn(3))` একটি trainable parameter তৈরি করছে।

এখানে `requires_grad=True` implicit থাকে। তার মানে training-এর সময় এই parameter-এর gradient calculate হবে এবং optimizer এটি update করতে পারবে।

---

## 4. Perceptron Class Explanation

### Cell 9
এটি notebook-এর core অংশ।

```python
class Perceptron(nn.Module):
```
এখানে custom neural network model define করা হয়েছে। `nn.Module` inherit করার কারণ হলো PyTorch যেন এটিকে proper model হিসেবে বুঝতে পারে।

### `__init__` method
`input_size` বোঝায় প্রতি sample-এ কতটি feature আছে।

```python
self.weight = nn.Parameter(torch.randn(input_size))
```
এখানে input-এর প্রতিটি feature-এর জন্য একটি weight রাখা হয়েছে। যদি `input_size = 3` হয়, তাহলে weight হবে `[w1, w2, w3]`।

```python
self.bias = nn.Parameter(torch.zeros(1))
```
Bias model-কে flexibility দেয়। Bias না থাকলে model-এর decision boundary origin-এর সাথে অতিরিক্তভাবে depend করতে পারে।

### `forward()` method
```python
z = x @ self.weight + self.bias
```
এখানে dot product করা হচ্ছে।

যদি:
\[x = [1,2,3], \; w = [0.5,-1,2], \; b = 0.1\]
তাহলে:
\[z = 1(0.5) + 2(-1) + 3(2) + 0.1 = 4.6\]

তারপর:
```python
y_pred = torch.sigmoid(z)
```
Sigmoid output-কে 0 থেকে 1 এর মধ্যে নিয়ে আসে। Binary classification-এ এটি probability হিসেবে useful।

Sigmoid formula:
\[\sigma(z) = \frac{1}{1 + e^{-z}}\]

যদি `z = 4.6` হয়, তাহলে output প্রায় `0.99` হবে। মানে model class 1-এর প্রতি খুব confident।

### `perceptron = Perceptron(3)`
এখানে 3-feature input-এর জন্য perceptron instance তৈরি করা হয়েছে।


## 5. Forward Pass, Model Setup, Loss, Optimizer

### Cell 10
```python
x = torch.tensor([1.0, 2.0, 3.0])
output = perceptron(x)
```
এখানে single input vector model-এ পাঠানো হয়েছে। `perceptron(x)` call করলে internally `forward(x)` execute হয়। Output হবে sigmoid probability।

### Cell 11
এখানে training-এর জন্য একটি নতুন model object তৈরি করা হয়েছে এবং যদি `my_model.pth` file আগে থেকে থাকে তাহলে load করা হচ্ছে।

```python
if os.path.exists(model_path):
    model.load_state_dict(torch.load(model_path))
```
এর purpose হলো training resume করা। যদি আগের session-এ model train হয়ে save হয়ে থাকে, তাহলে zero থেকে শুরু না করে previous weights নিয়ে continue করা যায়।

### Cell 12
`torch.randn(3)` দিয়ে random input বানানো হয়েছে। এটি dummy input, model test করার জন্য useful।

### Cell 13
`y_pred = model(x)` দিয়ে random input-এর উপর prediction দেখা হয়েছে। এর main purpose হলো model forward computation ঠিক আছে কি না check করা।

### Cell 14
`print(*model.parameters())` model-এর trainable parameters print করে। এখানে weight ও bias দেখতে পাওয়া যাবে। Training-এর আগে ও পরে compare করলে বোঝা যায় model শিখেছে কি না।

### Cell 15
এটি training-এর core setup:

```python
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)
```

#### `BCELoss` কী?
Binary Cross Entropy loss binary classification-এর জন্য ব্যবহৃত হয়।

Formula:
\[L = -[y\log(\hat{y}) + (1-y)\log(1-\hat{y})]\]

এখানে:
- `y` = actual label
- `ŷ` = predicted probability

যদি actual = 1 এবং prediction = 0.99 হয়, loss কম হবে। কিন্তু actual = 1 আর prediction = 0.01 হলে loss অনেক বেশি হবে।

#### `Adam` optimizer কী?
Adam একটি widely used optimizer, যা gradient ব্যবহার করে weight update করে। এটি adaptive learning rate ব্যবহার করে এবং practical deep learning-এ খুব common।

Gradient descent intuition:
\[w_{new} = w_{old} - \eta \frac{\partial L}{\partial w}\]
এখানে `η` হলো learning rate।

---

## 6. Training Dataset ও Shape Understanding

### Cell 16
এখানে training data `X` এবং target `Y` define করা হয়েছে।

`X` shape `(4, 3)` অর্থাৎ 4টি sample এবং প্রতি sample-এ 3টি feature।
`Y` shape `(4, 1)` অর্থাৎ 4টি label।

Data intuition:
- প্রথম 3টি sample-এর target = 0
- শেষ sample-এর target = 1

এটি একটি toy binary classification dataset। Real-world data না, কিন্তু training pipeline বোঝানোর জন্য useful।

### Cell 17
`y_pred = model(X)` দিয়ে batch prediction নেওয়া হয়েছে।

এখানে matrix operation হচ্ছে:
\[(4,3) \cdot (3,) \rightarrow (4,)\]
মানে 4টি sample-এর জন্য একসাথে prediction আসছে। এটিই batch processing।

### Cell 18
এখানে tensor dimension (`ndim`) এবং `unsqueeze()` নিয়ে কাজ করা হয়েছে।

যদি `y_pred.shape = (4,)` হয়, তাহলে:
- `unsqueeze(1)` করার পর shape `(4,1)`
- আবার `unsqueeze(1)` করলে shape `(4,1,1)`

এখানে main learning হলো: neural network-এ shape mismatch খুব common সমস্যা, তাই dimension understanding খুব important।

Practicalভাবে training-এর জন্য একবার `unsqueeze(axis=1)` যথেষ্ট। দ্বিতীয়বার unsqueeze মূলত demonstration।


## 7. Training Loop, Backpropagation, Evaluation, Save/Load

### Cell 19
এই cell-এ `train_model()` function define করা হয়েছে। এটি পুরো deep learning training cycle-এর সবচেয়ে গুরুত্বপূর্ণ অংশ।

### Step 1: Forward Propagation
```python
y_pred = model(X)
```
Input `X` model-এর মধ্যে যায় এবং prediction আসে।

### Step 2: Loss Calculation
```python
loss = criterion(y_pred.unsqueeze(axis=1), Y)
```
Prediction আর actual label compare করে error বের করা হচ্ছে।

### Step 3: Old Gradient Clear
```python
optimizer.zero_grad()
```
PyTorch default-এ gradient accumulate করে। তাই প্রতিটি নতুন epoch-এর আগে old gradient clear করা জরুরি।

### Step 4: Backpropagation
```python
loss.backward()
```
এখানে autograd loss থেকে weight ও bias-এর gradient বের করে। অর্থাৎ:
\[\frac{\partial L}{\partial w}, \frac{\partial L}{\partial b}\]

এগুলো বলে দেয় loss কমাতে parameter কোন দিকে update করতে হবে।

### Step 5: Weight Update
```python
optimizer.step()
```
Optimizer gradient ব্যবহার করে parameter update করে।

Update intuition:
\[w = w - \eta \frac{\partial L}{\partial w}\]
\[b = b - \eta \frac{\partial L}{\partial b}\]

### Step 6: Logging
প্রতি 1000 epoch পর loss print করা হচ্ছে, যাতে training progress monitor করা যায়। Loss কমলে বুঝতে পারি model pattern শিখছে।

### Cell 20
`train_model(model, 5000)` model-কে 5000 epoch train করে।

#### Epoch কী?
একবার পুরো training dataset model-এর মধ্যে pass হওয়া = 1 epoch।

এই dataset ছোট বলে 5000 epoch দেওয়া হয়েছে, যাতে pattern শেখা সহজ হয়।

### Cell 21
Training-এর পরে আবার `print(*model.parameters())` করা হয়েছে। এর মাধ্যমে updated weight ও bias দেখা যায়। এটি training হয়েছে কি না verify করার সহজ উপায়।

### Cell 22
এখানে evaluation function define করা হয়েছে:

```python
model.eval()
with torch.no_grad():
    test_output = model(X)
```

#### `model.eval()`
Model-কে evaluation mode-এ নেয়। Dropout বা BatchNorm-এর মতো layer থাকলে তাদের behaviour train mode আর eval mode-এ আলাদা হয়। যদিও এই notebook-এর perceptron-এ এই layer নেই, তবুও এটি best practice।

#### `torch.no_grad()`
Prediction-এর সময় gradient calculate বন্ধ রাখে। এতে speed বাড়ে এবং memory কম লাগে।

### Cell 23
এখানে `Y` print করে actual output দেখা হচ্ছে। Prediction আর ground truth পাশাপাশি compare করার জন্য actual label দেখা দরকার।

### Cell 24
`model.state_dict()` model-এর weight এবং bias dictionary আকারে দেখায়। সাধারণত output structure হবে:

```python
{'weight': tensor(...), 'bias': tensor(...)}
```

এটি PyTorch model persistence-এর standard structure।

### Cell 25
```python
torch.save(model.state_dict(), 'my_model.pth')
```
এখানে model-এর learned parameters file-এ save করা হচ্ছে। পরেরবার notebook run করলে এই saved parameters load করে training continue করা যাবে।

---

## 8. এই notebook-এর full workflow এক নজরে

```text
NumPy Array -> Torch Tensor -> Perceptron Define -> Weight/Bias Initialize
-> Forward Pass -> Sigmoid Output -> BCELoss
-> Backpropagation -> Adam Update -> Training Loop
-> Eval Mode -> Save Model
```

---

## 9. Core Concepts Summary

### Tensor
Deep learning-এর main data structure।

### Parameter
Trainable values, যেমন weight ও bias।

### Forward Pass
Input থেকে output prediction আসা।

### Activation Function
Sigmoid non-linearity introduce করে এবং output-কে probability range-এ আনে।

### Loss Function
Prediction কতটা ভুল হয়েছে তা মাপে।

### Backpropagation
Loss থেকে gradient বের করে।

### Optimizer
Gradient ব্যবহার করে parameter update করে।

### Evaluation Mode
Training ছাড়া efficient prediction করার mode।

### Model Save/Load
Learned parameter future use-এর জন্য file-এ সংরক্ষণ করা।

---

## 10. Use Case

এই notebook real-world production model না, কিন্তু deep learning fundamentals শেখার জন্য খুব useful। এটি beginner-কে বুঝতে সাহায্য করে single perceptron কীভাবে কাজ করে এবং PyTorch training lifecycle কী।

---

## 11. Improvement Ideas

ভবিষ্যতে এই notebook improve করতে চাইলে নিচের জিনিস যোগ করা যেতে পারে:

- accuracy calculation
- threshold-based class prediction
- loss curve visualization
- actual vs predicted comparison
- multi-layer perceptron
- DataLoader use
- train/validation split

---

## 12. Final Takeaway

এই notebook মূলত দেখায় কীভাবে PyTorch ব্যবহার করে একটি simple perceptron model define, train, evaluate, এবং save করতে হয়। যদি তুমি এই notebook-এর flow ভালোভাবে বুঝে ফেলো, তাহলে পরের step হবে multi-layer neural network, activation comparison, loss visualization, এবং real dataset-এ training practice করা।
