In [113]:
#Mac: pip3 install torch torchvision

In [114]:
import numpy as np
import torch
import torch.nn as nn

In [115]:
#normal numpy array
X = np.array([
    [0.0, 0.0],
    [0.0, 1.0],
    [1.0, 0.0],
    [1.0, 1.0],
])
print(type(X))

<class 'numpy.ndarray'>


In [116]:
# convert the np array to py torch tensor
X = torch.tensor(X)
print(type(X))

<class 'torch.Tensor'>


In [117]:
np.random.rand(5) #random array

array([0.36743248, 0.57077707, 0.77797515, 0.65234315, 0.22347246])

In [118]:
my_tensor = torch.rand(5) #random tensor array
print(my_tensor)

tensor([0.7894, 0.3610, 0.0077, 0.2604, 0.8600])


In [119]:
my_tensor.sum(axis=0) #sum of the tensor array

tensor(2.2785)

In [120]:
torch.randn(3) #pull random numbers from normal distribution where std = 1, mean = 0

tensor([0.3156, 0.5535, 0.6693])

In [121]:
# Neural Network Parameter
nn.Parameter(torch.randn(3)) # requires_grad=True -> during training, these parameters will be optimized and calculate gradient

Parameter containing:
tensor([ 0.6506,  0.7705, -1.3090], requires_grad=True)

In [122]:
#Define Perceptron, we need input(x), weights(w), bias(b), calculation(z), activation function
class Perceptron(nn.Module):
    def __init__(self, input_size):
        super(Perceptron, self).__init__() #We want the features of nn.Module in our parent class Perceptron. Without this, PyTorch will not understand
                                           # that it's a neuran network

        self.input_size = input_size #store total no of input(x) size / no of features in each input

        self.weight = nn.Parameter(torch.randn(input_size)) #we know, all input (X) has an corresponding weigh(W). so, input_size == no of weight
        self.bias = nn.Parameter(torch.zeros(1)) #Without bias (b), all result will went through origin. bias create flexibity [can shift anywhere]
                                                 # nn.Parameter() -> Trainable Parameters (will apply optimizer, gradient, etc.)

        print(self.weight, self.bias)

    def forward(self, x): #Here, we'll write the prediction logics
        z = x @ self.weight + self.bias #@ means means matrix multiplication / dot product and z = X.W + b = x1w1  + x2w2 + ---- + xnwn + b
        y_pred = torch.sigmoid(z) #push the z to a non-linear activation function 'sigmoid'.
                                  #Why sigmoid? -> Useful for binary classification. 0 → negative and 1 → positive
        return y_pred

# When ever well call perceptron(x), internally PyTorch calls forward(x)

perceptron = Perceptron(3) #here, x = [x1, x2, x3] -> 3 features

Parameter containing:
tensor([ 1.1487,  0.4334, -1.2934], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)


In [123]:
x = torch.tensor([1.0, 2.0, 3.0])
output = perceptron(x) #When ever well call perceptron(x), internally PyTorch calls forward(x)
print(output)

tensor([0.1341], grad_fn=<SigmoidBackward0>)


In [124]:
#Define model
import os

model = Perceptron(input_size=3) #input_size = 3 means 3 features in each input
model_path = 'my_model.pth' #define a path for save our model

if os.path.exists(model_path):
    model.load_state_dict(torch.load(model_path)) #load if there is any existing learned model. Sometimes we face interruped and we need to restart. 
                                                  #So, using this method, we can start with existing situation so that we don't need to start from beginning.
    print("Model Loaded...")

Parameter containing:
tensor([-1.0872, -0.1003, -0.2467], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)
Model Loaded...


In [125]:
#input(x)
x = torch.randn(3)
print(x)

tensor([ 1.0932, -1.3281,  0.4498])


In [126]:
#prediction/output(y)
y_pred = model(x)
print(y_pred)

tensor([0.0661], grad_fn=<SigmoidBackward0>)


In [127]:
#see the parameters of our model
print(*model.parameters())

Parameter containing:
tensor([-0.3142,  1.3949,  0.0475], requires_grad=True) Parameter containing:
tensor([-0.4729], requires_grad=True)


In [128]:
# Cost Function
criterion = nn.BCELoss() #Bynary Cross Entropy Loss - used for binary classification

#Optimizer - used for optimize the loss/cost
optimizer = torch.optim.Adam(
    model.parameters(), #we need to optimize the model's parameters
    lr=0.0001 #define learning rate
)

In [129]:
# select input (X), output (Y)
X = torch.Tensor(
    [
        [0.0, 0.0, 0.0], # sample input 1 (x1, x2, x3)
        [0.0, 1.0, 0.0], # sample input 2
        [1.0, 0.0, 0.0], # sample input 3
        [1.0, 1.0, 1.0]  # sample input 4
    ]
) #shape (4, 3) -> Row/Batch size 4 (total input), Col 3 (no of features in each sample). Batch processing: (4,3)⋅(3,)=(4,)
# (batch_size, features) = (4,3)

Y = torch.Tensor(
    [
        [0.0], # sample output 1
        [0.0], # sample output 2
        [0.0], # sample output 3
        [1.0]  # sample output 4
    ]
)

In [130]:
y_pred = model(X) # means perceptron.forward(X)
print(y_pred)

tensor([0.3839, 0.7155, 0.3128, 0.6582], grad_fn=<SigmoidBackward0>)


In [131]:
print(y_pred.ndim)
print(y_pred)
y_pred = y_pred.unsqueeze(axis=1) #unsqueeze() -> add a dimension. We did this for creating a batch output. 
                                  #eural networks standardize tensors as (batch_size, output_features)
print(y_pred.ndim)
print(y_pred)
y_pred = y_pred.unsqueeze(axis=1) # unsqueeze() -> add a dimension
print(y_pred.ndim)
print(y_pred)

1
tensor([0.3839, 0.7155, 0.3128, 0.6582], grad_fn=<SigmoidBackward0>)
2
tensor([[0.3839],
        [0.7155],
        [0.3128],
        [0.6582]], grad_fn=<UnsqueezeBackward0>)
3
tensor([[[0.3839]],

        [[0.7155]],

        [[0.3128]],

        [[0.6582]]], grad_fn=<UnsqueezeBackward0>)


In [132]:
#model training
def train_model(model, epochs):
    for epoch in range(epochs):
        """ Prediction (Forward Propagation) """
        y_pred = model(X) # (Backward propagation) -> produce input to output
        
        """ Loss calculation """
        loss = criterion(y_pred.unsqueeze(axis=1), Y) # calculate loss using predict output(y_pred) and true output Y (original)

        """ Calculate gradient """
        optimizer.zero_grad() #finding the optimal points [local minima] where loss is minimum
        loss.backward() # (Backward propagation)

        """ Update weight """
        optimizer.step() # w1 = w1 - lr * dw1, here, lr = steps, dw = direction
        
        if epoch % 1000 == 0:
            print(f'Epoch: {epoch}, Loss: {loss.item():.4f}')

In [133]:
train_model(model, 5000)

Epoch: 0, Loss: 0.6337
Epoch: 1000, Loss: 0.5902
Epoch: 2000, Loss: 0.5502
Epoch: 3000, Loss: 0.5135
Epoch: 4000, Loss: 0.4798


In [134]:
print(*model.parameters())

Parameter containing:
tensor([0.1590, 0.9476, 0.5455], requires_grad=True) Parameter containing:
tensor([-0.9498], requires_grad=True)


In [135]:
#Model Evaluation
""" Mode of a torch model

By default: train
We can set the mode to eval during prediction
"""
def predict(model, X):
    model.eval() # without evaluation mode, it will calculate gradient which is very time consuming and unnecessary. 
    with torch.no_grad():
        test_output = model(X)
    return test_output

predict(model, X)

tensor([0.2789, 0.4994, 0.3120, 0.6687])

In [136]:
# actual output
Y

tensor([[0.],
        [0.],
        [0.],
        [1.]])

In [137]:
model.state_dict() #crate weigh, bias dictonary, [key, value] pair

OrderedDict([('weight', tensor([0.1590, 0.9476, 0.5455])),
             ('bias', tensor([-0.9498]))])

In [138]:
torch.save(model.state_dict(), 'my_model.pth') # save the model's weights and bias in the specific path
# if we re-run from beginning, out model will start from previous/saved weight, bias. It will improve from previous. 