In [1]:
""" Class 5. Numpy For AI Engineers

Objectives:
1. An Introduction to Data Science 
2. Role of a Data Scientist
3. Numpy basics
4. Advanced Numpy Methods
"""
!pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

print(np.__version__)

2.2.6


In [3]:
""" An Introduction to Data Science

Data: 
123 (yes)
ABC (yes)
010111101 (yes)

Information: Meaningful data.
Example: 4537 iexm lokv (no meaning to us. Data)
         I eat rice. (has meaning. Information)
         
Data Science: A science that extracts insights 
from raw data and assist business for data 
driven decision making.

Role of Data Scientist:
1. Data Management: Converts raw data to processed data for analysis.
2. Data Preprocessing: Converts the processed data to preproccessed 
   data for AI algorithm.
   For example: "I eat rice" is processed into relevant values 
                 [23, 145, 47].
3. Feature Engineering and Exploratory Data Analysis: Selects only top most relevant data (features)
Table: Name    | Roll | Course 1 | Course 2 | Course 3 | Address | CGPA
         Masum |  258 |   75     |    85    |    89    | Dhaka   | 3.89
         
Features: Name, Roll, Course 1, Course 2, Course 3, Address, CGPA
Task: Predict CGPA.

Input: (Name, Roll, Course 1, Course 2, Course 3, Address) 
Output: CGPA
Input ("Masum", "258", 75, 85, 89, Dhaka) -> Algorithm -> 3.89 (Bad Feature Engineering)
      (75, 85, 89) => 3.89 (Good Feature Engineering)

4. Model Selection: Selects an appropriate model for Machine learning.
5. Evaluation: Evaluates the models performance.
6. Deploy: Develops systems for real life 
7. Monitor: Monitors the performance of machine learning.

Career Opportunities:
Step 1-3 (Data Analyst)
Step 1-5 (Data Scientist)
Step 1-7 (Machine Learning Engineers)

Image (100 x 100) is a set of pixels.
Total pixels: 100 x 100 = 10000
Each pixel is a feature

Map 10000 pixels -> lower 100 pixels (dimensionality reduction, 99%)
Example algorithm: Principal Component Analysis, Linear Discriminant Analysis 
"""
print("Numpy For AI Engineers")

Numpy For AI Engineers


In [4]:
"""
Numpy Basics
- Numpy stands for numerical python
- NumPy is a Python library.
- NumPy is used for working with arrays. 
- 50x faster than list
Installation: pip install numpy
"""

my_list = [1, 2, 3, 4, 5, 6]
print(my_list, type(my_list))
my_np_array = np.array(my_list)
print(my_np_array, type(my_np_array))

[1, 2, 3, 4, 5, 6] <class 'list'>
[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [5]:
my_np_array.dtype

dtype('int64')

In [6]:
my_np_array.shape

(6,)

In [7]:
my_np_array.ndim

1

In [8]:
""" Create an array with all zeros
The default dtype is float64.
"""

zeros_np_array = np.zeros(
    shape=(6,2),
    dtype='int'
)

print(zeros_np_array)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [9]:
""" Create an array with all ones
We explicitly set the dtype to int here.
"""
ones_np_array = np.ones(
    shape=(3,2),
    dtype='int32'
)

print(ones_np_array)

[[1 1]
 [1 1]
 [1 1]]


In [10]:
assigned_with_specific_np_array = np.full(
    shape=(10,),
    fill_value=5,
)
assigned_with_specific_np_array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [11]:
""" Create an identity matrix
A square matrix with ones on the main diagonal and zeros elsewhere.
I4 (4x4 identity matrix)
"""

id_matrix = np.eye(4)
print(f"\nIdentity matrix:\n{id_matrix}")


Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
""" Create an empty array
The elements are not initialized and may contain arbitrary memory values.
"""
my_empty_np_array = np.empty(
    shape=(5,3),
)
print(f"\nEmpty array:\n{my_empty_np_array}") # 4.9e-324 = 4.9 / 10^324 ~ 0.000000000000....000011


Empty array:
[[4.67296746e-307 1.69121096e-306 4.67293691e-307]
 [1.11256817e-306 1.06811422e-306 1.42417221e-306]
 [1.11260619e-306 8.90094053e-307 1.86919378e-306]
 [1.06809792e-306 1.37962456e-306 1.69111861e-306]
 [1.78020169e-306 7.56605918e-307 5.33590898e-322]]


In [13]:
""" Type cast 
Conversion from one data type to another compatible data type using .astype().
"""
my_empty_np_array_int = my_empty_np_array.astype('int')
print(my_empty_np_array_int)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
""" Create a sequential array (similar to Python's range)
np.arange(start, stop, step) - stop is exclusive
Default: step=1
"""

my_array = np.arange(start=1, stop=11, step=1)
print(f"Sequential array (arange): {my_array}")

Sequential array (arange): [ 1  2  3  4  5  6  7  8  9 10]


In [15]:
""" Create a linearly spaced array
np.linspace(start, stop, num) - stop is inclusive
The array has 'num' equally spaced samples between start and stop.
"""

my_np_array = np.linspace(
    start=2,
    stop=10,
    num=5
)

print(f"Linearly spaced array (linspace): {my_np_array}")

Linearly spaced array (linspace): [ 2.  4.  6.  8. 10.]


In [16]:
""" Multidimensional numpy arrays 
    Mathematical Objects: 
    Scalar (0D), Vector (1D), Matrix (2D), Tensor (xD where x > 2)
"""

scalar = np.array(39)
scalar.ndim

0

In [17]:
vector = np.array([1, 2, 3])
vector.ndim

1

In [18]:
matrix = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

matrix.ndim

2

In [19]:
tensor = np.array(
    [[[[1]]]]
)
tensor.ndim

4

In [20]:
""" Numpy indexing: Finding the locations
1. Non-negative indexing (0, 1, 2, ...)
2. Negative indexing (-1, -2, -3, ...)
"""

my_1d_array = np.array([1, 2, 3, 4, 5])

print(my_1d_array[0])
print(my_1d_array[-5])

1
1


In [21]:
my_2d_array = np.array(
    [[1, 2, 3, 4],
     [5, 8, 9, 5],
     [7, 1, 2, 7]]
) 

print(my_2d_array[1,2])
print(my_2d_array[-2,2])
print(my_2d_array.shape)

9
9
(3, 4)


In [22]:
my_3d_array = np.array(
    [
        [ 
            [1, 2],
            [3, 4],
            [1, 1]
        ],
        [
            [7, 8],
            [5, 10],
            [1, 2]
        ],
    ]
)

my_3d_array.shape

(2, 3, 2)

In [23]:
my_3d_array[1,1,1]

np.int64(10)

In [24]:
my_list

[1, 2, 3, 4, 5, 6]

In [25]:
sub_list = my_list[1:4]
sub_list

[2, 3, 4]

In [26]:
""" Numpy Slicing 
    - arguments with default values: start=0, stop=n, step=1
    - array_name[start:stop:step]
    - Default values: start=0, stop=n, step=1
    - stop index is excluded
"""
print('Array:', my_1d_array)
print('Slicing')
print(my_1d_array[1:4:1]) 
print(my_1d_array[1::])

Array: [1 2 3 4 5]
Slicing
[2 3 4]
[2 3 4 5]


In [27]:
my_1d_array[::]

array([1, 2, 3, 4, 5])

In [28]:
my_1d_array[::-1]

array([5, 4, 3, 2, 1])

In [29]:
print('Array')
print(my_2d_array)
print('Slicing')

print(my_2d_array[1::,1:3])

Array
[[1 2 3 4]
 [5 8 9 5]
 [7 1 2 7]]
Slicing
[[8 9]
 [1 2]]


In [30]:
"""
Shape (3, 4) -> reshape into (4, 3), (12, 1) (Possible)
             -> reshape into (3, 5) (Impossible)
"""


'\nShape (3, 4) -> reshape into (4, 3), (12, 1) (Possible)\n             -> reshape into (3, 5) (Impossible)\n'

In [31]:
""" Numpy reshape: Changing the shape of an array
Condition: Number of elements must be same.

Technique:
----------
Flatten the original array:
[1, 2, 3 4, 5, 6 7, 8, 9 10, 11, 12 13, 14, 15]
Reshape as desired shape:
[ 
   [[1, 2, 3 4, 5], [6 7, 8, 9 10], [11, 12 13, 14, 15]]
]
shape: (1, 3, 5)

Example:

[
        [
            [1, 2],
            [3, 4]
        ],
        [
            [7, 8],
            [5, 10]
        ],
]

ndim = 3
shape = (2, 2, 2)
So, total number of elements = 2 x 2 x 2 = 8
Reshape into (4, 1, 2). 

Step 1: Flatten the original array:
  At dimension 2, 
  [
        [
            1, 2, 3, 4
        ],
        [
            7, 8, 5, 10
        ],
 ]
 
 At dimension 1,
 [
        1, 2, 3, 4, 7, 8, 5, 10
 ]
 So, flattened array, [1, 2, 3, 4, 7, 8, 5, 10]
 
Step 2: Reshape into (4, 1, 2).
  At dimension 0, 
  [
     [1, 2],
     [3, 4],
     [7, 8],
     [5, 10]
  ]
  
  At dimension 1,
  [
     [
       [1, 2]
     ],
     [
       [3, 4]
     ],
     [
       [7, 8]
     ],
     [
       [5, 10]
     ]
  ]
  
"""

my_2d_array = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12],
     [13, 14, 15]]
)

print(my_2d_array.shape)
my_2d_array_reshaped = my_2d_array.reshape(1, 3, 5)
print(my_2d_array_reshaped)

(5, 3)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [32]:
""" Reshape with -1 """
my_np_array = np.zeros(shape=(3, 4, 2, 2))
# number of elements: 3 x 4 x 2 x 2 = 48
my_np_array_reshaped = my_np_array.reshape(2, -1, 12)
print(my_np_array_reshaped.shape)

(2, 2, 12)


In [34]:
"""Numpy Filtering"""

# Method 1
my_1d_array = np.array([1, 2, 3, 4, 5, 6])
filter_mask = [True, True, True, False, True, False]

filtered_array = my_1d_array[filter_mask]
filtered_array

array([1, 2, 3, 5])

In [37]:
print(my_1d_array[5])

6


In [39]:
print(my_1d_array[[2, 3, 4, 5]])

[3 4 5 6]


In [40]:
indices = [0, 2, 5]
filtered_array = my_1d_array[indices]
print(filtered_array)

[1 3 6]


In [42]:
# my_1d_array = [1, 2, 3, 4, 5, 6]
indices = [0, 5, 2, 1]
filtered_array = my_1d_array[indices]
print(filtered_array)

[1 6 3 2]


In [48]:
""" Vectorization refers to the process of performing operations 
on entire arrays (or vectors) without the need for explicit loops.

Example: Add 5 to each element of the array [1, 2, 3, 4]
Naive solution:
for i in range(4):
    my_1d_array[i] += 5

Vectorization:
    my_1d_array += 5
"""

print(my_1d_array)
odd_mask = my_1d_array % 2
odd_mask = odd_mask.astype('bool')
print(odd_mask)
my_1d_array[odd_mask]

[1 2 3 4 5 6]
[ True False  True False  True False]


array([1, 3, 5])

In [49]:
my_1d_array = my_1d_array + 5
print(my_1d_array)

[ 6  7  8  9 10 11]


In [50]:
my_1d_array = my_1d_array * 2
print(my_1d_array)

[12 14 16 18 20 22]


In [59]:
""" Broadcasting 

- converting a lower shape into higher shape for vectorization
- condition: requires that the arrays involved in the operation 
either have the same size in each dimension or that one of the arrays has a size of 1 in that dimension.

Example: An array of shape (6, 7) and (6, 1). So these are compatible with broadcasting.
Array 1 shape (6, 7, 8)
Array 2 shape (1, 7, 8)
. So broadcasting is possible.

Array 1 shape (6, 7, 8)
Array 2 shape (6, 1, 4)
"""

w = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12]]
)
x = np.array(
    [[10, 20, 30],
     [10, 20, 30],
     [10, 20, 30],
     [10, 20, 30]]
)

x_broadcast = x = np.array(
    [[10, 20, 30],
     [10, 20, 30],
     [10, 20, 30],
     [10, 20, 30]]
)

print(w.shape, x.shape)

(4, 3) (4, 3)


In [60]:
print(w * x)

[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]
 [100 220 360]]


In [61]:
print(w * x_broadcast)

[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]
 [100 220 360]]


In [66]:
""" Numpy Axis

First dimension: axis=0
Second dimension: axis=1
Third dimension: axis=2
..
Nth dimension: axis=N-1
"""

my_np_array = np.array(
    [
        [1, 5, -2],
        [0, 1, 9]
    ]
)

my_np_array.shape

(2, 3)

In [67]:
print(np.sum(my_np_array, axis=1))

[ 4 10]


In [68]:
print(np.sum(my_np_array, axis=0))

[1 6 7]


In [72]:
my_np_3d = np.array(
    [
        [[2, 2],    # 2d
         [1, 1]],
        
        [[3, 1],    # 2d     
         [4, 3]],
        
        [[9, -2],   # 2d
         [1, 1]]
    ]
)

print(my_np_3d.shape)

(3, 2, 2)


In [78]:
sum = np.sum(my_np_3d, axis=1)
sum.shape

(3, 2)

In [79]:
print(sum)

[[ 3  3]
 [ 7  4]
 [10 -1]]


In [80]:
""" numpy random 

- rand(): returns a random value between [0, 1]
- randint(x): returns a random value between [0, x) 
- randint(x, size): returns a random array between [0, x) of size
- shuffle(): shuffle an array
"""

print(np.random.rand())
print(np.random.rand(2, 5))

print(type(np.random.rand(5)))

0.5907162086851542
[[0.59028957 0.73864142 0.19234644 0.18416929 0.99578938]
 [0.97649589 0.91185194 0.56903704 0.32837595 0.67227363]]
<class 'numpy.ndarray'>


In [89]:
print(np.random.randint(100))

52


In [132]:
np.random.seed(42)
my_array = np.random.randint(100, size=(5,2))
print(my_array)

[[51 92]
 [14 71]
 [60 20]
 [82 86]
 [74 74]]


In [128]:
np.random.shuffle(my_array)
print(my_array)

[[64 67]
 [67  9]
 [83 21]
 [36 87]
 [44 47]]


In [96]:
""" Useful methods """

probabilities = np.array([0.3, 0.1, 0.4, 0.2])

probabilities_sorted = np.sort(probabilities)
print(probabilities_sorted)

probabilities_reverse_sorted = np.sort(probabilities)[::-1]
print(probabilities_reverse_sorted)

[0.1 0.2 0.3 0.4]
[0.4 0.3 0.2 0.1]


In [98]:
""" Argmax, Argmin """

index_max = np.argmax(probabilities)
print(index_max)

index_min = np.argmin(probabilities)
print(index_min)

2
1


In [103]:
""" Split """

my_np_array = np.array([1, 5, 1, 1, 5, 7])

new_np_array = np.split(
    my_np_array, 
    indices_or_sections=3
)
print(new_np_array)
print(new_np_array[0])
print(new_np_array[1])
print(new_np_array[2])

[array([1, 5]), array([1, 1]), array([5, 7])]
[1 5]
[1 1]
[5 7]


In [104]:
my_np_array_1 = np.array(
    [1, 2, 3]
)

my_np_array_2 = np.array(
    [3, 4, 3]
)

print(my_np_array_1)
print(my_np_array_2)

dot_product = np.dot(my_np_array_1, my_np_array_2)
print(dot_product)

[1 2 3]
[3 4 3]
20


In [105]:
""" matrix transpose """
my_2d_array_1 = np.array(
    [[2, 1, 3],
     [7, 5, 6]]
)

print(my_2d_array_1.shape)
print(my_2d_array_1.T)
print(my_2d_array_1.T.shape)

(2, 3)
[[2 7]
 [1 5]
 [3 6]]
(3, 2)


In [107]:
print(my_np_array_1)

print(np.mean(my_np_array_1))
print(np.median(my_np_array_1))
print(np.std(my_np_array_1))

[1 2 3]
2.0
2.0
0.816496580927726
