In [ ]:
""" Class 5. Numpy For AI Engineers

Objectives:
1. An Introduction to Data Science 
2. Role of a Data Scientist
3. Numpy basics
4. Advanced Numpy Methods
"""
!pip install numpy

In [4]:
import numpy as np

print(np.__version__)

2.2.6


In [3]:
""" An Introduction to Data Science

Data: 
123 (yes)
ABC (yes)
010111101 (yes)

Information: Meaningful data.
Example: 4537 iexm lokv (no meaning to us. Data)
         I eat rice. (has meaning. Information)
         
Data Science: A science that extracts insights 
from raw data and assist business for data 
driven decision making.

Role of Data Scientist:
1. Data Management: Converts raw data to processed data for analysis.
2. Data Preprocessing: Converts the processed data to preproccessed 
   data for AI algorithm.
   For example: "I eat rice" is processed into relevant values 
                 [23, 145, 47].
3. Feature Engineering and Exploratory Data Analysis: Selects only top most relevant data (features)
Table: Name    | Roll | Course 1 | Course 2 | Course 3 | Address | CGPA
         Masum |  258 |   75     |    85    |    89    | Dhaka   | 3.89
         
Features: Name, Roll, Course 1, Course 2, Course 3, Address, CGPA
Task: Predict CGPA.

Input: (Name, Roll, Course 1, Course 2, Course 3, Address) 
Output: CGPA
Input ("Masum", "258", 75, 85, 89, Dhaka) -> Algorithm -> 3.89 (Bad Feature Engineering)
      (75, 85, 89) => 3.89 (Good Feature Engineering)

4. Model Selection: Selects an appropriate model for Machine learning.
5. Evaluation: Evaluates the models performance.
6. Deploy: Develops systems for real life 
7. Monitor: Monitors the performance of machine learning.

Career Opportunities:
Step 1-3 (Data Analyst)
Step 1-5 (Data Scientist)
Step 1-7 (Machine Learning Engineers)

Image (100 x 100) is a set of pixels.
Total pixels: 100 x 100 = 10000
Each pixel is a feature

Map 10000 pixels -> lower 100 pixels (dimensionality reduction, 99%)
Example algorithm: Principal Component Analysis, Linear Discriminant Analysis 
"""
print("Numpy For AI Engineers")

Numpy For AI Engineers


In [14]:
"""
Numpy Basics
- Numpy stands for numerical python
- NumPy is a Python library.
- NumPy is used for working with arrays. 
- 50x faster than list
Installation: pip install numpy
"""

my_list = [1, 2, 3, 4, 5, 6]
print(my_list, type(my_list))
my_np_array = np.array(my_list)
print(my_np_array, type(my_np_array))

[1, 2, 3, 4, 5, 6] <class 'list'>
[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [15]:
my_np_array.dtype

dtype('int64')

In [17]:
my_np_array.shape

(6,)

In [16]:
my_np_array.ndim

1

In [26]:
""" Create an array with all zeros
The default dtype is float64.
"""

zeros_np_array = np.zeros(
    shape=(6,2),
    dtype='int'
)

print(zeros_np_array)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [28]:
""" Create an array with all ones
We explicitly set the dtype to int here.
"""
ones_np_array = np.ones(
    shape=(3,2),
    dtype='int32'
)

print(ones_np_array)

[[1 1]
 [1 1]
 [1 1]]


In [32]:
assigned_with_specific_np_array = np.full(
    shape=(10,),
    fill_value=5,
)
assigned_with_specific_np_array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [34]:
""" Create an identity matrix
A square matrix with ones on the main diagonal and zeros elsewhere.
I4 (4x4 identity matrix)
"""

id_matrix = np.eye(4)
print(f"\nIdentity matrix:\n{id_matrix}")


Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [41]:
""" Create an empty array
The elements are not initialized and may contain arbitrary memory values.
"""
my_empty_np_array = np.empty(
    shape=(5,3),
)
print(f"\nEmpty array:\n{my_empty_np_array}") # 4.9e-324 = 4.9 / 10^324 ~ 0.000000000000....000011


Empty array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [45]:
""" Type cast 
Conversion from one data type to another compatible data type using .astype().
"""
my_empty_np_array_int = my_empty_np_array.astype('int')
print(my_empty_np_array_int)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [57]:
""" Create a sequential array (similar to Python's range)
np.arange(start, stop, step) - stop is exclusive
Default: step=1
"""

my_array = np.arange(start=1, stop=11, step=1)
print(f"Sequential array (arange): {my_array}")

Sequential array (arange): [ 1  2  3  4  5  6  7  8  9 10]


In [55]:
""" Create a linearly spaced array
np.linspace(start, stop, num) - stop is inclusive
The array has 'num' equally spaced samples between start and stop.
"""

my_np_array = np.linspace(
    start=2,
    stop=10,
    num=5
)

print(f"Linearly spaced array (linspace): {my_np_array}")

Linearly spaced array (linspace): [ 2.  4.  6.  8. 10.]


In [58]:
""" Multidimensional numpy arrays 
    Mathematical Objects: 
    Scalar (0D), Vector (1D), Matrix (2D), Tensor (xD where x > 2)
"""

scalar = np.array(39)
scalar.ndim

0

In [59]:
vector = np.array([1, 2, 3])
vector.ndim

1

In [60]:
matrix = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

matrix.ndim

2

In [61]:
tensor = np.array(
    [[[[1]]]]
)
tensor.ndim

4

In [62]:
""" Numpy indexing: Finding the locations
1. Non-negative indexing (0, 1, 2, ...)
2. Negative indexing (-1, -2, -3, ...)
"""

my_1d_array = np.array([1, 2, 3, 4, 5])

print(my_1d_array[0])
print(my_1d_array[-5])

1
1


In [64]:
my_2d_array = np.array(
    [[1, 2, 3, 4],
     [5, 8, 9, 5],
     [7, 1, 2, 7]]
) 

print(my_2d_array[1,2])
print(my_2d_array[-2,2])
print(my_2d_array.shape)

9
9
(3, 4)


In [66]:
my_3d_array = np.array(
    [
        [ 
            [1, 2],
            [3, 4],
            [1, 1]
        ],
        [
            [7, 8],
            [5, 10],
            [1, 2]
        ],
    ]
)

my_3d_array.shape

(2, 3, 2)

In [67]:
my_3d_array[1,1,1]

np.int64(10)

In [68]:
my_list

[1, 2, 3, 4, 5, 6]

In [69]:
sub_list = my_list[1:4]
sub_list

[2, 3, 4]

In [75]:
""" Numpy Slicing 
    - arguments with default values: start=0, stop=n, step=1
    - array_name[start:stop:step]
    - Default values: start=0, stop=n, step=1
    - stop index is excluded
"""
print('Array:', my_1d_array)
print('Slicing')
print(my_1d_array[1:4:1]) 
print(my_1d_array[1::])

Array: [1 2 3 4 5]
Slicing
[2 3 4]
[2 3 4 5]


In [76]:
my_1d_array[::]

array([1, 2, 3, 4, 5])

In [77]:
my_1d_array[::-1]

array([5, 4, 3, 2, 1])

In [84]:
print('Array')
print(my_2d_array)
print('Slicing')

print(my_2d_array[1::,1:3])

Array
[[1 2 3 4]
 [5 8 9 5]
 [7 1 2 7]]
Slicing
[[8 9]
 [1 2]]


In [85]:
"""
Shape (3, 4) -> reshape into (4, 3), (12, 1) (Possible)
             -> reshape into (3, 5) (Impossible)
"""


(3, 4)

In [87]:
""" Numpy reshape: Changing the shape of an array
Condition: Number of elements must be same.

Technique:
----------
Flatten the original array:
[1, 2, 3 4, 5, 6 7, 8, 9 10, 11, 12 13, 14, 15]
Reshape as desired shape:
[ 
   [[1, 2, 3 4, 5], [6 7, 8, 9 10], [11, 12 13, 14, 15]]
]
shape: (1, 3, 5)

Example:

[
        [
            [1, 2],
            [3, 4]
        ],
        [
            [7, 8],
            [5, 10]
        ],
]

ndim = 3
shape = (2, 2, 2)
So, total number of elements = 2 x 2 x 2 = 8
Reshape into (4, 1, 2). 

Step 1: Flatten the original array:
  At dimension 2, 
  [
        [
            1, 2, 3, 4
        ],
        [
            7, 8, 5, 10
        ],
 ]
 
 At dimension 1,
 [
        1, 2, 3, 4, 7, 8, 5, 10
 ]
 So, flattened array, [1, 2, 3, 4, 7, 8, 5, 10]
 
Step 2: Reshape into (4, 1, 2).
  At dimension 0, 
  [
     [1, 2],
     [3, 4],
     [7, 8],
     [5, 10]
  ]
  
  At dimension 1,
  [
     [
       [1, 2]
     ],
     [
       [3, 4]
     ],
     [
       [7, 8]
     ],
     [
       [5, 10]
     ]
  ]
  
"""

my_2d_array = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12],
     [13, 14, 15]]
)

print(my_2d_array.shape)
my_2d_array_reshaped = my_2d_array.reshape(1, 3, 5)
print(my_2d_array_reshaped)

(5, 3)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [93]:
""" Reshape with -1 """
my_np_array = np.zeros(shape=(3, 4, 2, 2))
# number of elements: 3 x 4 x 2 x 2 = 48
my_np_array_reshaped = my_np_array.reshape(2, -1, 12)
print(my_np_array_reshaped.shape)

(2, 2, 12)
